### ISSUE TITLE
[renderer1] [error] [Extension Host] Error: Unexpected SIGPIPE

### ISSUE THREAD

**Issue by nik-kor** [phoityne/hdx4vsc#17]
Hello!

I followed your install instructions and everything seems to be working but when I tried to "Start debugging", looks like nothing happens - no errors, but no visible feedback. 

The only logs I could find was in `Log(Window)` saing 
```
[2022-05-17 00:03:54.059] [renderer1] [error] [Extension Host] Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/share/code/resources/app/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
```
Seems like debugger had never started but the IDE fails before with some unknown error.

Here is my environment:
```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-107-generic
```

**Comment by phoityne** [comment]
Hi.

Is there any log messages on the terminal window in the vscode ?
or  the phoityne.log file in the .vscode folder of your haskell project folder ?

In the launch.json, there is a "logLevel" property,
could you set "DEBUG" level ?

Regards.

**Comment by nik-kor** [comment]
Hi @phoityne 
Nothing except the line with `Unexpected SIGPIPE` in `Log(Window)`.

Here is the config I tried(only changed the logLevel as you suggested):
```

        {
            "type": "ghc",
            "request": "launch",
            "name": "haskell(stack)",
            "internalConsoleOptions": "openOnSessionStart",
            "workspace": "${workspaceFolder}",
            "startup": "${workspaceFolder}/test/Spec.hs",
            "startupFunc": "",
            "startupArgs": "",
            "stopOnEntry": false,
            "mainArgs": "",
            "ghciPrompt": "H>>= ",
            "ghciInitialPrompt": "> ",
            "ghciCmd": "stack ghci --test --no-load --no-build --main-is TARGET -fprint-evld-with-show",
            "ghciEnv": {},
            "logFile": "${workspaceFolder}/.vscode/phoityne.log",
            "logLevel": "DEBUG",
            "forceInspect": true
        },
```
